name: Front-end

on:
  pull_request:
    types: [opened, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "Checkout repository"
      - name: Build
        run: echo "Build"
      - name: Test
        run: echo "Testing"
      - name: Create environment
        run: echo "Create environment"
      - name: Deploy
        run: echo "Deploy"
      - name: Smoke test
        run: echo "Smoke test"
