name: Front-end

on:
  pull_request:
    types: [opened, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "Checkout repository"
      - name: Build
        run: echo "Build"
    
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: test
